
import __ASTRO_IMAGE_IMPORT_1wu62G from "/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F4.md";
import __ASTRO_IMAGE_IMPORT_1Oh8qL from "/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F3.md";
import __ASTRO_IMAGE_IMPORT_274aOQ from "/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F2.md";
import __ASTRO_IMAGE_IMPORT_2oQddV from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F1.md";
import __ASTRO_IMAGE_IMPORT_1eH3DB from "/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F5.md";
import __ASTRO_IMAGE_IMPORT_VU1fw from "/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F6.md";
import __ASTRO_IMAGE_IMPORT_Z4PJOr from "/src/images/speakers/emil-steiner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Femil-steiner.md";
import __ASTRO_IMAGE_IMPORT_1KKM1l from "/src/images/speakers/javier-garcia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fjavier-garcia.md";
import __ASTRO_IMAGE_IMPORT_3L6QH from "/src/images/speakers/martina-rossi.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fmartina-rossi.md";
import __ASTRO_IMAGE_IMPORT_Z1BGfTD from "/src/images/speakers/anna-muller.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fanna-muller.md";
import __ASTRO_IMAGE_IMPORT_ZhxsMH from "/src/images/speakers/sofia-hagblom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fsofia-hagblom.md";
import __ASTRO_IMAGE_IMPORT_J2czp from "/src/images/speakers/miguel-santos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fmiguel-santos.md";
import __ASTRO_IMAGE_IMPORT_2jqcce from "/src/images/sponsors/medium.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fmedium.md";
import __ASTRO_IMAGE_IMPORT_Z62ECJ from "/src/images/sponsors/google.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fgoogle.md";
import __ASTRO_IMAGE_IMPORT_1DdC48 from "/src/images/sponsors/polar-sh.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fpolar-sh.md";
import __ASTRO_IMAGE_IMPORT_19W0CJ from "/src/images/sponsors/swissted.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fswissted.md";
export default new Map([["/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F4.md", __ASTRO_IMAGE_IMPORT_1wu62G], ["/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F3.md", __ASTRO_IMAGE_IMPORT_1Oh8qL], ["/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F2.md", __ASTRO_IMAGE_IMPORT_274aOQ], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F1.md", __ASTRO_IMAGE_IMPORT_2oQddV], ["/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F5.md", __ASTRO_IMAGE_IMPORT_1eH3DB], ["/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F6.md", __ASTRO_IMAGE_IMPORT_VU1fw], ["/src/images/speakers/emil-steiner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Femil-steiner.md", __ASTRO_IMAGE_IMPORT_Z4PJOr], ["/src/images/speakers/javier-garcia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fjavier-garcia.md", __ASTRO_IMAGE_IMPORT_1KKM1l], ["/src/images/speakers/martina-rossi.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fmartina-rossi.md", __ASTRO_IMAGE_IMPORT_3L6QH], ["/src/images/speakers/anna-muller.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fanna-muller.md", __ASTRO_IMAGE_IMPORT_Z1BGfTD], ["/src/images/speakers/sofia-hagblom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fsofia-hagblom.md", __ASTRO_IMAGE_IMPORT_ZhxsMH], ["/src/images/speakers/miguel-santos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fmiguel-santos.md", __ASTRO_IMAGE_IMPORT_J2czp], ["/src/images/sponsors/medium.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fmedium.md", __ASTRO_IMAGE_IMPORT_2jqcce], ["/src/images/sponsors/google.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fgoogle.md", __ASTRO_IMAGE_IMPORT_Z62ECJ], ["/src/images/sponsors/polar-sh.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fpolar-sh.md", __ASTRO_IMAGE_IMPORT_1DdC48], ["/src/images/sponsors/swissted.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fswissted.md", __ASTRO_IMAGE_IMPORT_19W0CJ]]);
		