
import __ASTRO_IMAGE_IMPORT_274aOQ from "/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F2.md";
import __ASTRO_IMAGE_IMPORT_2oQddV from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F1.md";
import __ASTRO_IMAGE_IMPORT_1eH3DB from "/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F5.md";
import __ASTRO_IMAGE_IMPORT_VU1fw from "/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F6.md";
import __ASTRO_IMAGE_IMPORT_1Oh8qL from "/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F3.md";
import __ASTRO_IMAGE_IMPORT_1wu62G from "/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F4.md";
import __ASTRO_IMAGE_IMPORT_2uLu7q from "/src/images/people/francis-wang.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Ffrancis-wang.md";
import __ASTRO_IMAGE_IMPORT_1L9Gez from "/src/images/initiatives/ai-ready-workforce.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Fai-native-workforce.md";
import __ASTRO_IMAGE_IMPORT_2SSAI from "/src/images/people/james-cheng.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fjames-cheng.md";
import __ASTRO_IMAGE_IMPORT_ZRSjTS from "/src/images/initiatives/industry-4-0.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Findustry-4-0-coalition.md";
import __ASTRO_IMAGE_IMPORT_Zl35kj from "/src/images/initiatives/ecosystem-mapping.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Finnovation-ecosystem-mapping.md";
import __ASTRO_IMAGE_IMPORT_ZFLjgT from "/src/images/initiatives/innovation-sanctuary.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Finnovation-sanctuary.md";
import __ASTRO_IMAGE_IMPORT_1d3bCw from "/src/images/initiatives/institutional-memory.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Finstitutional-memory.md";
import __ASTRO_IMAGE_IMPORT_Z2wnwVE from "/src/images/initiatives/capturing-waynism.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Fcapturing-waynism.md";
import __ASTRO_IMAGE_IMPORT_2aXhTq from "/src/images/initiatives/crossing-the-chasm.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Fstrategic-adaptation.md";
import __ASTRO_IMAGE_IMPORT_hE9jW from "/src/images/entities/waterloo-conrad.png?astroContentImageFlag=&importer=src%2Fcontent%2Fentities%2Fconrad-school.md";
import __ASTRO_IMAGE_IMPORT_Zn1h5f from "/src/images/entities/bet300-server.png?astroContentImageFlag=&importer=src%2Fcontent%2Fentities%2Fbet300-ecoop-community.md";
export default new Map([["/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F2.md", __ASTRO_IMAGE_IMPORT_274aOQ], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F1.md", __ASTRO_IMAGE_IMPORT_2oQddV], ["/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F5.md", __ASTRO_IMAGE_IMPORT_1eH3DB], ["/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F6.md", __ASTRO_IMAGE_IMPORT_VU1fw], ["/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F3.md", __ASTRO_IMAGE_IMPORT_1Oh8qL], ["/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2F4.md", __ASTRO_IMAGE_IMPORT_1wu62G], ["/src/images/people/francis-wang.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Ffrancis-wang.md", __ASTRO_IMAGE_IMPORT_2uLu7q], ["/src/images/initiatives/ai-ready-workforce.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Fai-native-workforce.md", __ASTRO_IMAGE_IMPORT_1L9Gez], ["/src/images/people/james-cheng.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fjames-cheng.md", __ASTRO_IMAGE_IMPORT_2SSAI], ["/src/images/initiatives/industry-4-0.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Findustry-4-0-coalition.md", __ASTRO_IMAGE_IMPORT_ZRSjTS], ["/src/images/initiatives/ecosystem-mapping.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Finnovation-ecosystem-mapping.md", __ASTRO_IMAGE_IMPORT_Zl35kj], ["/src/images/initiatives/innovation-sanctuary.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Finnovation-sanctuary.md", __ASTRO_IMAGE_IMPORT_ZFLjgT], ["/src/images/initiatives/institutional-memory.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Finstitutional-memory.md", __ASTRO_IMAGE_IMPORT_1d3bCw], ["/src/images/initiatives/capturing-waynism.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Fcapturing-waynism.md", __ASTRO_IMAGE_IMPORT_Z2wnwVE], ["/src/images/initiatives/crossing-the-chasm.png?astroContentImageFlag=&importer=src%2Fcontent%2Finitiatives%2Fstrategic-adaptation.md", __ASTRO_IMAGE_IMPORT_2aXhTq], ["/src/images/entities/waterloo-conrad.png?astroContentImageFlag=&importer=src%2Fcontent%2Fentities%2Fconrad-school.md", __ASTRO_IMAGE_IMPORT_hE9jW], ["/src/images/entities/bet300-server.png?astroContentImageFlag=&importer=src%2Fcontent%2Fentities%2Fbet300-ecoop-community.md", __ASTRO_IMAGE_IMPORT_Zn1h5f]]);
		